import React, { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import kyc from '../../services/kyc';

const modes = [
    ['off', 'Off', 'Every submission stays with your team.'],
    ['shadow', 'Shadow', 'Measure performance without influencing reviewers.'],
    ['advisory', 'Advisory', 'Show findings. Your team makes every decision.'],
    ['auto_approve', 'Auto-approve', 'Approve clear matches. Ask for better photos when needed.'],
    ['full_auto', 'Full auto', 'Also allow identity-mismatch rejection when enabled.'],
];
const types = [['national_id', 'National ID'], ['passport', 'Passport'], ['driving_licence', 'Driving licence'], ['alien_id', 'Alien / refugee ID']];
const defaults = { mode: 'off', mode_per_platform: {}, paused: false, reject_requires_second_opinion_per_platform: {}, auto_reject_enabled: false, auto_reject_enabled_per_platform: {}, reject_requires_second_opinion: true, ladder: ['google/gemini-3.8-flash', 'openai/gpt-5.4-mini'], second_opinion_model: 'anthropic/claude-sonnet-5', approve_threshold: .95, reject_threshold: .98, daily_cap_usd: 5, qa_sample_pct: 10, document_types_per_platform: {} };

export default function KycAiSettings({ value, onChange, platforms = [] }) {
    const form = { ...defaults, ...value };
    const [market, setMarket] = useState('');
    const [advanced, setAdvanced] = useState(false);
    const report = useQuery({ queryKey: ['kyc-ai-report', market], queryFn: () => kyc.aiReport(market), refetchInterval: 30000 });
    const backlog = useMutation({ mutationFn: () => kyc.aiBacklog(Number(market)), onSuccess: () => report.refetch() });
    const update = (key, val) => onChange({ ...form, [key]: val });
    const override = form.mode_per_platform?.[market];
    const mode = market ? override || form.mode : form.mode;
    const documents = form.document_types_per_platform?.[market] || ['national_id', 'passport', 'driving_licence'];
    const rejectEnabled = market ? form.auto_reject_enabled_per_platform?.[market] ?? form.auto_reject_enabled : form.auto_reject_enabled;
    const numeric = (key, label, min, max, step = 1) => <label className="block text-xs font-semibold text-slate-600" key={key}>{label}<input type="number" min={min} max={max} step={step} value={form[key]} onChange={(event) => update(key, event.target.value === '' ? '' : Number(event.target.value))} className="crm-input mt-2 w-full" /></label>;
    return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white">
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 bg-slate-50 px-5 py-5"><div><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Automation & quality</p><h3 className="mt-1 text-lg font-semibold text-slate-900">An extra pair of eyes</h3><p className="mt-1 max-w-xl text-sm text-slate-500">Choose how much the verification assistant can do. New markets start with automation off.</p></div><label className="text-xs font-medium text-slate-600">Settings for<select value={market} onChange={(event) => setMarket(event.target.value)} className="crm-select mt-1 block min-w-[180px]"><option value="">Global defaults</option>{platforms.map((p) => <option key={p.id} value={p.id}>{p.name || p.platform_name}</option>)}</select></label></div>
        <div className="space-y-6 p-5">
            {market ? <label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={!override} onChange={(event) => { const map = { ...form.mode_per_platform }; if (event.target.checked) delete map[market]; else map[market] = form.mode; update('mode_per_platform', map); }} />Use global mode ({form.mode.replaceAll('_', ' ')})</label> : null}
            <label className="flex items-start gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700"><input type="checkbox" checked={form.paused} onChange={(event) => update('paused', event.target.checked)} className="mt-1" /><span><strong className="block font-semibold">Pause all automated checks</strong><span className="mt-1 block text-xs text-slate-500">Stops new checks and prevents running checks from changing a status, in every market.</span></span></label>
            <fieldset><legend className="mb-3 text-sm font-semibold text-slate-900">Review mode</legend><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{modes.map(([key, label, description]) => <label key={key} className={`relative flex cursor-pointer flex-col gap-2 rounded-lg border p-3 ${key === mode ? 'border-teal-600 bg-teal-50' : 'border-slate-200 hover:bg-slate-50'}`}><span className="flex items-center justify-between gap-2 text-sm font-semibold text-slate-900">{label}<input type="radio" name="kyc-ai-mode" value={key} checked={key === mode} onChange={() => market ? update('mode_per_platform', { ...form.mode_per_platform, [market]: key }) : update('mode', key)} className="text-teal-700" /></span><span className="text-xs leading-5 text-slate-500">{description}</span></label>)}</div></fieldset>
            {report.data?.provider_configured === false ? <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Add your OpenRouter key in SEO Engine → Provider API keys before running checks. Submissions still go to the human queue.</p> : null}
            <p className="border-l-2 border-slate-300 pl-3 text-xs leading-5 text-slate-500">Unreadable date of birth, under-18 documents, model refusals and failed checks always go to a person. Stage names are never compared with legal names.</p>
            {mode === 'full_auto' ? <div className="space-y-3 rounded-lg border border-amber-200 bg-amber-50 p-4"><label className="flex gap-3 text-sm text-slate-800"><input type="checkbox" checked={rejectEnabled} onChange={(event) => market ? update('auto_reject_enabled_per_platform', { ...form.auto_reject_enabled_per_platform, [market]: event.target.checked }) : update('auto_reject_enabled', event.target.checked)} />Allow automatic rejection for a clear identity mismatch</label><label className="flex gap-3 text-sm text-slate-800"><input type="checkbox" checked={market ? form.reject_requires_second_opinion_per_platform?.[market] ?? form.reject_requires_second_opinion : form.reject_requires_second_opinion} onChange={(event) => market ? update('reject_requires_second_opinion_per_platform', {...form.reject_requires_second_opinion_per_platform, [market]: event.target.checked}) : update('reject_requires_second_opinion', event.target.checked)} />Require agreement from a second model</label></div> : null}
            {market ? <fieldset><legend className="mb-2 text-sm font-semibold text-slate-900">Accepted documents in this market</legend><div className="flex flex-wrap gap-3">{types.map(([key, label]) => <label key={key} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700"><input type="checkbox" checked={documents.includes(key)} disabled={documents.length === 1 && documents.includes(key)} onChange={(event) => update('document_types_per_platform', { ...form.document_types_per_platform, [market]: event.target.checked ? [...documents, key] : documents.filter((v) => v !== key) })} />{label}</label>)}</div></fieldset> : null}
            <div className="grid gap-4 sm:grid-cols-2">{numeric('daily_cap_usd', 'Daily budget · USD (all markets)', 0, 1000, .25)}{numeric('qa_sample_pct', 'AI approvals sampled for human QA · %', 0, 100)}</div>
            <div className="rounded-lg bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-sm font-semibold text-slate-900">Calibration · last 14 days</h4><p className="mt-1 text-xs text-slate-500">Compare human decisions before increasing automation.</p></div>{report.data ? <p className="text-xs tabular-nums text-slate-500">Today: ${Number(report.data.spent_today).toFixed(3)} spent · ${Number(report.data.reserved_today).toFixed(2)} reserved</p> : null}</div>
                {report.isLoading ? <p className="mt-4 text-sm text-slate-500">Loading comparison…</p> : report.isError ? <p role="alert" className="mt-4 text-sm text-amber-800">Could not load the report. <button type="button" onClick={() => report.refetch()} className="underline">Try again</button></p> : report.data?.models?.length ? <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-2 font-medium">Model</th><th className="pb-2 font-medium">Human agreement</th><th className="pb-2 font-medium">Failed / declined</th></tr></thead><tbody>{report.data.models.map((row) => <tr key={row.model || 'pending'} className="border-t border-slate-200"><td className="py-3 text-slate-700">{row.model || 'Not started'}</td><td className="py-3 tabular-nums text-slate-700">{row.compared ? `${row.agreed} / ${row.compared}` : 'Awaiting human decisions'}</td><td className="py-3 tabular-nums text-slate-700">{row.failed} failed · {row.declined || 0} declined</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-slate-500">No completed comparisons yet. Shadow mode builds your first baseline.</p>}
                {market ? <div className="mt-4 border-t border-slate-200 pt-4"><button type="button" onClick={() => backlog.mutate()} disabled={backlog.isPending} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-700 disabled:opacity-50">{backlog.isPending ? 'Queueing…' : 'Check eligible submissions in this market'}</button><p className="mt-2 text-xs leading-5 text-slate-500">Uses saved settings. Only complete, consented submissions are eligible; the daily budget still applies.</p>{backlog.data ? <p role="status" className="mt-2 text-xs text-teal-700">{backlog.data.queued} queued · {backlog.data.skipped} skipped</p> : null}{backlog.error ? <p role="alert" className="mt-2 text-xs text-amber-800">{backlog.error.response?.data?.message || 'Could not queue checks.'}</p> : null}</div> : null}
            </div>
            <button type="button" className="text-xs font-semibold text-slate-600 underline underline-offset-4" aria-expanded={advanced} onClick={() => setAdvanced(!advanced)}>{advanced ? 'Hide model settings' : 'Model settings & confidence thresholds'}</button>
            {advanced ? <div className="grid gap-4 border-t border-slate-200 pt-4 sm:grid-cols-2">{[0,1].map((index) => <label key={index} className="text-xs font-semibold text-slate-600">{index ? 'Fallback model' : 'Primary model'}<input value={form.ladder[index] || ''} onChange={(event) => {const ladder = [...form.ladder]; ladder[index] = event.target.value; update('ladder', ladder);}} className="crm-input mt-2 w-full" /></label>)}<label className="text-xs font-semibold text-slate-600">Second-opinion model<input value={form.second_opinion_model} onChange={(event) => update('second_opinion_model', event.target.value)} className="crm-input mt-2 w-full" /></label>{numeric('approve_threshold', 'Approval confidence · 0.90–1.00', .9, 1, .01)}{numeric('reject_threshold', 'Rejection confidence · 0.95–1.00', .95, 1, .01)}<p className="text-xs leading-5 text-slate-500">Only zero-retention providers with structured output are eligible. Budget reservations include room for a fallback and second opinion.</p></div> : null}
            <p className="text-xs text-slate-500">Use “Save KYC settings” below to apply these changes.</p>
        </div>
    </section>;
}
