import React from 'react';
import { channelLabels, money } from '../RebatesTab';

export default function RebateProgramEditor({ draft: d, setDraft, editable, currency, budget, conflict }) {
    const set = (path, value) => setDraft(prev => { const next = structuredClone(prev); const keys = path.split('.'); let target = next; keys.slice(0, -1).forEach(k => { target = target[k]; }); target[keys.at(-1)] = value; return next; });
    const field = (label, path, suffix = currency) => {
        const value = path.split('.').reduce((o, k) => o[k], d);
        return <label className="rbt-field">{label}<span className="rbt-input"><input type="number" min="0" max={suffix === '%' ? 50 : 100000000} step={suffix === '%' ? '.1' : '1'} value={value} onChange={e => set(path, e.target.value === '' ? '' : Number(e.target.value))} /><span>{suffix}</span></span></label>;
    };
    const toggle = (label, path, note) => <label className="rbt-toggle"><input type="checkbox" checked={path.split('.').reduce((o, k) => o[k], d)} onChange={e => set(path, e.target.checked)} /><span className="rbt-switch" aria-hidden="true" /><span><b>{label}</b>{note && <small>{note}</small>}</span></label>;
    const selfRates = ['wallet', 'self_checkout'].filter(k => d.self.channels[k].on).map(k => Number(d.self.channels[k].pct));
    const assistedTooHigh = ['staff_link', 'sales_assisted'].some(k => d.self.channels[k].on && selfRates.length && Number(d.self.channels[k].pct) >= Math.min(...selfRates));
    return <fieldset className="rbt-editor" disabled={!editable}>
        <section className="rbt-card"><div className="rbt-card-title"><div><span className="rbt-step">01</span><h5>Top-up rebate</h5><p>Higher top-ups earn the rate for their tier.</p></div>{toggle('Enabled', 'topup.on')}</div><div className="rbt-ladder" aria-label="Top-up tier preview">{d.topup.tiers.map((t, i) => <div key={i}><b>{t.pct}%</b><span>from {money(t.min, currency)}</span></div>)}</div><div className="rbt-tier-head"><span>Minimum top-up</span><span>Rate</span><span /></div>{d.topup.tiers.map((t, i) => <div className="rbt-tier" key={i}>{field(`Tier ${i + 1} minimum`, `topup.tiers.${i}.min`)}{field(`Tier ${i + 1} rate`, `topup.tiers.${i}.pct`, '%')}<button type="button" aria-label={`Remove tier ${i + 1}`} disabled={d.topup.tiers.length === 1} onClick={() => set('topup.tiers', d.topup.tiers.filter((_, j) => i !== j))}>×</button></div>)}<button type="button" className="rbt-link" disabled={d.topup.tiers.length >= 12} onClick={() => set('topup.tiers', [...d.topup.tiers, { min: Number(d.topup.tiers.at(-1).min) + 1000, pct: Number(d.topup.tiers.at(-1).pct) }])}>+ Add a tier</button><div className="rbt-divider">{field('Maximum rebate per top-up', 'topup.cap')}</div></section>
        <section className="rbt-card"><div className="rbt-card-title"><div><span className="rbt-step">02</span><h5>Activation & renewal</h5><p>A separate switch and rate for every paid channel.</p></div>{toggle('Enabled', 'self.on')}</div><div className="rbt-channel-label">Companion pays herself</div>{['wallet', 'self_checkout', 'manual_submission'].map(k => <div className="rbt-channel" key={k}>{toggle(channelLabels[k], `self.channels.${k}.on`)}{field(`${channelLabels[k]} rate`, `self.channels.${k}.pct`, '%')}</div>)}<div className="rbt-channel-label">Staff-assisted</div>{['staff_link', 'sales_assisted'].map(k => <div className="rbt-channel" key={k}>{toggle(channelLabels[k], `self.channels.${k}.on`)}{field(`${channelLabels[k]} rate`, `self.channels.${k}.pct`, '%')}</div>)}{assistedTooHigh && <p role="status" className="rbt-warning">Assisted rates match or beat self-service. Paying herself no longer earns the better deal.</p>}<p className="rbt-never"><b>Never qualifies</b> Manual activation without payment, M-Pesa imports, bundles and free trials. Sandbox payments are simulated.</p>{field('Maximum rebate per activation', 'self.cap')}{conflict?.self_service_incentive?.enabled && <p className="rbt-warning">The existing {conflict.self_service_incentive.percent}% self-service discount is replaced while rebates are active. Pausing restores it.</p>}</section>
        <section className="rbt-card"><div className="rbt-card-title"><div><span className="rbt-step">03</span><h5>Boosters</h5><p>One welcome bonus, and a reason to stay active.</p></div></div>{toggle('First top-up bonus', 'first.on', 'Only the first completed self-paid top-up can earn this bonus.')}<div className="rbt-fields">{field('Bonus amount', 'first.amount')}{field('Minimum first top-up', 'first.min')}</div><div className="rbt-divider">{toggle('Automatic renewal bonus', 'renew.on', 'Added after the wallet rebate, within the monthly cap.')}{field('Additional rate', 'renew.pct', '%')}</div></section>
        <section className="rbt-card"><div className="rbt-card-title"><div><span className="rbt-step">04</span><h5>Guardrails</h5><p>Control spend without interrupting payments.</p></div></div><div className="rbt-fields">{field('Per companion, per month', 'guard.monthly_cap')}{field('Market monthly budget', 'guard.budget')}</div><div className="rbt-budget"><div><span>{money(budget.issued, currency)} issued this month</span><b>{budget.budget ? Math.round(100 * budget.issued / budget.budget) : 0}%</b></div><progress value={budget.issued} max={Math.max(1, budget.budget)} /><small>Current budget: {money(budget.budget, currency)}. After the first real rebate is credited, the monthly budget stays fixed; edits then apply next month.</small></div>{toggle('Stack top-up and wallet activation rebates', 'guard.stack', 'When off, wallet-paid activations and automatic renewals earn no rebate.')}</section>
        <section className="rbt-card"><div className="rbt-card-title"><div><span className="rbt-step">05</span><h5>Audience & schedule</h5><p>Start small, then publish when the market is ready.</p></div></div><label className="rbt-field">Rollout<select value={d.rollout_mode} onChange={e => set('rollout_mode', e.target.value)}><option value="off">Off</option><option value="sandbox">Sandbox · test companions only</option><option value="live">Live</option></select></label>{d.rollout_mode === 'sandbox' && <label className="rbt-field">Test companion CRM IDs<input value={d.test_client_ids.join(', ')} onChange={e => set('test_client_ids', e.target.value.split(',').map(v => Number(v.trim())).filter(Boolean))} placeholder="2514" /><small>Sandbox records quotes in the ledger. It never credits the wallet.</small></label>}<div className="rbt-fields">{['starts_at', 'ends_at'].map(k => <label className="rbt-field" key={k}>{k === 'starts_at' ? 'Starts (your local time)' : 'Ends (your local time)'}<input type="datetime-local" value={d[k] ? new Date(new Date(d[k]).getTime() - new Date(d[k]).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''} onChange={e => set(k, e.target.value ? new Date(e.target.value).toISOString() : null)} /></label>)}</div>{toggle('Verified companions only', 'audience.verified_only')}{toggle('Include agency profiles', 'audience.include_agency')}<label className="rbt-field">Companion label<input maxLength={80} value={d.copy.label} onChange={e => set('copy.label', e.target.value)} /></label></section>
    </fieldset>;
}
