import React from 'react';
import { useQuery } from '@tanstack/react-query';
import api from '../../../services/api';
import { channelLabels, errorMessage, money } from '../RebatesTab';

export default function RebatePerformance({ marketId, currency }) {
    const q = useQuery({ queryKey: ['rebates-performance', marketId], queryFn: () => api.get(`/crm/settings/billing/rebates/${marketId}/performance`).then(r => r.data), staleTime: 30_000 });
    if (q.isLoading) return <p className="rbt-empty" role="status">Loading rebate performance…</p>;
    if (q.isError) return <p className="rbt-error" role="alert">{errorMessage(q.error)} <button onClick={() => q.refetch()}>Retry</button></p>;
    const d = q.data;
    const exportRows = () => {
        const lines = [['Trigger', 'Channel', 'Grants', 'Issued', 'Currency'], ...d.by_trigger.map(r => [r.trigger, r.channel, r.grants, r.issued, currency])];
        const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([lines.map(row => row.join(',')).join('\n')], { type: 'text/csv' })); a.download = `rebates-performance-${marketId}-${d.cost_period}.csv`; a.click(); URL.revokeObjectURL(a.href);
    };
    return <div className="rbt-performance"><div className="rbt-performance-heading"><div><h5>Is the reward changing behaviour?</h5><p>Production payments only. Volume measures cover the last 30 days; issuance covers {d.cost_period}.</p></div><button onClick={exportRows}>Export summary</button></div><div className="rbt-metrics">{[['Rebates issued', money(d.issued, currency), `of ${money(d.budget.budget, currency)} budget`], ['Self-service share', `${d.self_service_share}%`, 'of subscription payment volume'], ['Wallet adoption', `${d.wallet_adoption}%`, 'of paying companions'], ['Average self-paid top-up', money(d.average_self_paid_topup, currency), 'last 30 days'], ['Cost / collected cash', `${d.cost_share}%`, 'issuance cost / cash collected']].map(([label, value, note]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div><div className="rbt-performance-grid"><section className="rbt-card"><h5>Weekly self-service share</h5>{!d.weekly.length ? <p className="rbt-hint">No production subscription payments yet. Sandbox activity stays in the ledger.</p> : <div className="rbt-bars">{d.weekly.map(w => <div key={w.week}><span>{new Date(`${w.week}T12:00:00`).toLocaleDateString('en', { month: 'short', day: 'numeric' })}</span><progress max="100" value={w.total ? 100 * w.self_paid / w.total : 0} /><b>{w.total ? Math.round(100 * w.self_paid / w.total) : 0}%</b></div>)}</div>}</section><section className="rbt-card"><h5>Collected cash after rebate cost</h5><strong className="rbt-net">{money(d.net_after_issuance_cost, currency)}</strong><p className="rbt-hint">Collected top-ups and paid external subscriptions ({money(d.cash_revenue_30d, currency)}), less this month's rebate issuance. Wallet-paid subscriptions are excluded from collected cash.</p></section></div><section className="rbt-card"><h5>Where the rewards went</h5><div className="rbt-table-wrap"><table><thead><tr><th>Trigger</th><th>Channel</th><th>Grants</th><th>Issued</th></tr></thead><tbody>{d.by_trigger.map((r, i) => <tr key={i}><td>{r.trigger.replaceAll('_', ' ')}</td><td>{channelLabels[r.channel]}</td><td>{r.grants}</td><td>{money(r.issued, currency)}</td></tr>)}</tbody></table></div>{!d.by_trigger.length && <p className="rbt-hint">No wallet credits issued this month. Publish in Sandbox to verify the journey first.</p>}</section></div>;
}
