import React,{useState,useEffect} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import api from '../../services/api';
const field='min-h-11 rounded-md border border-slate-300 bg-white px-3 text-sm';
export default function LoveGifts({market,clientId,from,to,tests}) {
    const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[provider,setProvider]=useState(''),[environment,setEnvironment]=useState(''),[page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[action,setAction]=useState(null),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[adjustment,setAdjustment]=useState('');
    const params={platform_id:market||undefined,client_id:clientId||undefined,from:from||undefined,to:to||undefined,include_tests:tests,status:status||undefined,provider:provider||undefined,environment:environment||undefined,search:search||undefined,page};
    useEffect(()=>{setPage(1);if(!tests)setEnvironment('');},[market,clientId,from,to,tests]);
    const q=useQuery({queryKey:['love-gifts',params],queryFn:async()=>(await api.get('/crm/monetization/love',{params})).data});
    async function exportRows(){setBusy(true);try{const r=await api.get('/crm/monetization/love/export',{params,responseType:'blob'});const u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download='send-love.csv';a.click();URL.revokeObjectURL(u);}catch(e){setMessage('Export failed. Try again.');}finally{setBusy(false);}}
    async function submit(){setBusy(true);try{await api.post(`/crm/monetization/love/${action.id}/${action.type}`,{reason,provider_reference:reference,wallet_adjustment_id:adjustment?Number(adjustment):undefined});setAction(null);setMessage('Saved.');await q.refetch();}catch(e){setMessage(e.response?.data?.message||'Could not save.');}finally{setBusy(false);}}
    const open=(g,type)=>{setAction({id:g.id,type});setReason('');setReference('');setAdjustment('');setMessage('');};
    const d=q.data;
    return <div className="space-y-4"><div className="flex flex-wrap gap-3"><label className="text-xs text-slate-500">Search<input aria-label="Search gifts" className={field+' block'} placeholder="Creator or payment reference" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label className="text-xs text-slate-500">Status<select className={field+' block'} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['sent','pending_payment','failed','review','refunded'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label className="text-xs text-slate-500">Provider<select className={field+' block'} value={provider} onChange={e=>{setProvider(e.target.value);setPage(1);}}><option value="">All providers</option><option value="kopokopo">M-Pesa · KopoKopo</option><option value="pawapay">pawaPay</option></select></label><label className="text-xs text-slate-500">Environment<select className={field+' block'} value={environment} disabled={!tests} onChange={e=>{setEnvironment(e.target.value);setPage(1);}}><option value="">All environments</option><option value="production">Live</option><option value="sandbox">Sandbox</option></select></label><button className={field+' self-end'} onClick={exportRows} disabled={busy}>Export CSV</button></div>
        {q.isPending&&<p role="status">Loading love received…</p>}{q.isError&&<p role="alert">Could not load gifts. <button onClick={()=>q.refetch()}>Try again</button></p>}
        {d&&<><dl className="grid gap-3 sm:grid-cols-4">{[['Attempts',d.summary.attempts],['Sent',d.summary.sent],['Completion',d.summary.completion_rate+'%'],['Unique senders',d.summary.senders]].map(([k,v])=><div key={k} className="rounded-lg border border-slate-200 bg-white p-4"><dt className="text-xs text-slate-500">{k}</dt><dd className="mt-2 text-2xl font-semibold">{v}</dd></div>)}</dl>{d.totals.map(t=><div key={t.currency} className="rounded-lg border border-slate-200 bg-white p-4 text-sm">{t.currency} · Gross {Number(t.gross).toLocaleString()} · Average gift {Number(t.average).toLocaleString()} · Creator credit {Number(t.creator_credit).toLocaleString()}</div>)}
        <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['Payment','Recipient','Gift','Status','Private note','Actions'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{d.gifts.data.map(g=><tr key={g.id} className="border-t border-slate-100 align-top"><td className="p-3"><Link className="underline" to={`/payments?purpose=send_love&search=${encodeURIComponent(g.payment?.reference_number||'')}&test_visibility=${g.is_sandbox?'include':'hide'}`}>{g.payment?.reference_number||'Payment'}</Link><small className="block text-slate-500">{g.payment?.provider_key}{g.is_sandbox?' · Sandbox':''}</small></td><td className="p-3"><Link to={`/clients/${g.client_id}`}>{g.client?.name}</Link></td><td className="p-3 whitespace-nowrap">{g.currency} {Number(g.amount).toLocaleString()}<small className="block text-slate-500">{g.card_line}</small></td><td className="p-3">{g.status.replaceAll('_',' ')}{g.payment?.failure_reason&&<small className="block text-slate-500">{g.payment.failure_reason}</small>}</td><td className="p-3 max-w-xs">{g.message||g.message_state.replaceAll('_',' ')}<small className="block text-slate-500">{g.metadata_json?.reported_at?'Reported · ':''}{g.message_state==='hidden_by_creator'?'Hidden by creator · ':''}{g.visitor_phone_masked}{g.contact_shared?' · Contact shared':''}</small></td><td className="p-3">{d.can_manage&&<div className="flex flex-wrap gap-2">{g.message_state!=='removed_by_staff'&&<button className={field} onClick={()=>open(g,'remove-note')}>Remove note</button>}{g.contact_shared&&<button className={field} onClick={()=>open(g,'clear-contact')}>Clear shared number</button>}{['sent','review'].includes(g.status)&&<button className={field} onClick={()=>open(g,'refund')}>Record refund</button>}</div>}</td></tr>)}</tbody></table>{!d.gifts.data.length&&<p className="p-10 text-center text-sm text-slate-500">No gifts match these filters.</p>}</div><div className="flex items-center justify-between text-sm"><button className={field} disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {d.gifts.current_page} of {d.gifts.last_page}</span><button className={field} disabled={page>=d.gifts.last_page} onClick={()=>setPage(p=>p+1)}>Next</button></div>
        <div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border border-slate-200 bg-white p-4"><h3 className="font-semibold">Top creators</h3>{d.top_creators.map((c,i)=><p key={i} className="mt-2 text-sm">{c.client?.name} · {c.currency} {Number(c.gross).toLocaleString()} · {c.gifts} gifts</p>)}</div><div className="rounded-lg border border-slate-200 bg-white p-4"><h3 className="font-semibold">Failure reasons</h3>{d.failures.length?d.failures.map((f,i)=><p key={i} className="mt-2 text-sm">{f.failure_reason||'No provider reason'} · {f.count}</p>):<p className="mt-2 text-sm text-slate-500">No failures in this window.</p>}</div></div></>}
        {action&&<section aria-label="Gift action" className="space-y-3 rounded-lg border border-slate-300 bg-white p-5"><h3 className="font-semibold">{action.type.replaceAll('-',' ')}</h3><label className="block text-sm">Reason<input minLength="5" className={field+' w-full'} value={reason} onChange={e=>setReason(e.target.value)}/></label>{action.type==='refund'&&<><p className="text-sm text-slate-500">Refund the mobile money payment manually, then supply its reference and the PIN-approved wallet reversal ID.</p><label className="block text-sm">Provider refund reference<input className={field+' w-full'} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="block text-sm">Wallet reversal transaction ID<input className={field+' w-full'} value={adjustment} onChange={e=>setAdjustment(e.target.value)}/></label></>}<button className={field} disabled={busy||reason.length<5} onClick={submit}>Save action</button> <button className={field} onClick={()=>setAction(null)}>Cancel</button></section>}<p role="status">{message}</p></div>;
}
