import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../../services/api';
import { useToast } from '../../ToastProvider';

export default function McpKnowledgePanel({ canManage }) {
    const toast = useToast(); const queryClient = useQueryClient(); const [key, setKey] = useState('');
    const query = useQuery({ queryKey: ['mcp-knowledge'], queryFn: () => api.get('/crm/settings/mcp/knowledge').then((r) => r.data) });
    const stage = useMutation({ mutationFn: () => api.post('/crm/settings/mcp/knowledge/stage', { idempotency_key: key || crypto.randomUUID() }), onSuccess: () => { toast.success('Knowledge snapshot staged.'); queryClient.invalidateQueries({ queryKey: ['mcp-knowledge'] }); }, onError: (e) => toast.error(e.response?.data?.message || 'Knowledge staging failed.') });
    const promote = useMutation({ mutationFn: (id) => api.post(`/crm/settings/mcp/knowledge/versions/${id}/promote`), onSuccess: () => { toast.success('Knowledge release promoted.'); queryClient.invalidateQueries({ queryKey: ['mcp-knowledge'] }); } });
    if (query.isLoading) return <div className="crm-surface p-6 text-sm text-slate-500">Loading knowledge provenance…</div>;
    const data = query.data || {}; const active = data.active_release;
    return <section className="crm-surface overflow-hidden" data-testid="mcp-knowledge-panel"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-teal-700">Approved knowledge</p><h3 className="mt-1 text-lg font-semibold text-slate-950">Versioned reference context</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Remote documentation is staged first. Only a reviewed immutable snapshot reaches MCP.</p></div>{canManage ? <button className="rounded-md bg-teal-700 px-3 py-2 text-sm font-semibold text-white hover:bg-teal-800 disabled:opacity-50" disabled={stage.isPending} onClick={() => { const id = crypto.randomUUID(); setKey(id); stage.mutate(); }}>{stage.isPending ? 'Staging…' : 'Stage update'}</button> : null}</div><div className="grid gap-px bg-slate-200 sm:grid-cols-3"><Fact label="Active release" value={active?.ontology_version || 'Ontology not bootstrapped'} /><Fact label="Approved snapshots" value={String((data.versions || []).filter((version) => version.status === 'ready').length)} /><Fact label="Latest run" value={data.runs?.[0]?.status || 'None'} /></div><div className="divide-y divide-slate-100">{(data.versions || []).map((version) => <div className="flex flex-wrap items-center justify-between gap-3 p-4" key={version.id}><div><p className="font-medium text-slate-800">{version.version}</p><p className="mt-1 text-xs text-slate-500">{version.status} · {version.content_sha256?.slice(0, 12)}…</p></div>{canManage && version.status === 'ready' ? <button className="text-sm font-semibold text-teal-700 hover:text-teal-900" onClick={() => promote.mutate(version.id)}>Promote</button> : null}</div>)}{!(data.versions || []).length ? <div className="p-6 text-sm text-slate-500">No staged reference snapshot. The first sync creates an escaped, reviewable baseline.</div> : null}</div></section>;
}
function Fact({ label, value }) { return <div className="bg-white p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>; }
