import React, { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../../services/api';
import SendLoveSettings from './SendLoveSettings';
import MonetizationAutomation from './MonetizationAutomation';

const sections = ['Market & readiness', 'Pass pricing', 'Offers & limits', 'Surfaces & checkout', 'Automation', 'Send love'];
const fieldClass = 'min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-400';
const names = { photos_enabled: 'Private photos', videos_enabled: 'Private videos', single_enabled: 'Single-item offers', bundles_enabled: 'Fixed bundles', min_price: 'Minimum price', max_price: 'Maximum price', bundle_min_items: 'Minimum bundle items', bundle_max_items: 'Maximum bundle items', live_offer_limit: 'Live offer limit', upload_max_bytes: 'Upload limit (bytes)', max_video_seconds: 'Video limit (seconds)', profile_section: 'Profile private section', home_private_content: 'Home · Private photos & videos', videos_private_filter: 'Videos private filter', show_prices: 'Show prices on previews', activation_kill_switch: 'Pause new pass activation', checkout_kill_switch: 'Pause new purchases' };
const errorMessage = (error, fallback) => Object.values(error.response?.data?.errors || {}).flat()[0] || error.response?.data?.message || fallback;
function Check({ label, checked, onChange }) { return <label className="flex min-h-11 items-center justify-between gap-4 rounded-md border border-slate-200 px-3 py-2 text-sm"><span>{label}</span><input type="checkbox" className="h-4 w-4 accent-slate-900" checked={!!checked} onChange={e => onChange(e.target.checked)} /></label>; }
export default function MonetizationSettings() {
    const qc = useQueryClient();
    const [market, setMarket] = useState(() => new URLSearchParams(location.search).get('platform_id') || '');
    const [section, setSection] = useState(0), [form, setForm] = useState(null), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
    const query = useQuery({ queryKey: ['monetization-settings', market], queryFn: async () => (await api.get('/crm/settings/monetization', { params: { platform_id: market || undefined } })).data });
    useEffect(() => { const s = query.data?.market; if (s) setForm({ ...s, offer_policy: Object.fromEntries(Object.entries(s.offer_policy_json).map(([k,v])=>[k,typeof v==='boolean'?v:Number(v)])), surface_policy: s.surface_policy_json, checkout_policy: s.checkout_policy_json, delivery_policy: s.delivery_policy_json, expiry_video_policy: query.data.automation?.expiry, free_pass_policy: query.data.automation?.free_pass, teaser_policy: query.data.automation?.teaser, prices: s.prices.length ? s.prices : [{ duration_key: '2_weeks', duration_label: '2 Weeks', price: '300', subsidy_mode: 'percentage', subsidy_value: '20', is_active: true }, { duration_key: '1_month', duration_label: '1 Month', price: '500', subsidy_mode: 'fixed', subsidy_value: '100', is_active: true }] }); }, [query.data]);
    const update = (key, value) => setForm(s => ({ ...s, [key]: value }));
    const nested = (key, name, value) => setForm(s => ({ ...s, [key]: { ...s[key], [name]: value } }));
    async function save(e) {
        e.preventDefault(); setBusy(true); setMessage('');
        try { const { data } = await api.put(`/crm/settings/monetization/markets/${form.platform_id}`, { ...form, reason }); setMessage(data.sync.status === 'synced' && data.credentials.status === 'synced' ? 'Saved and synced to WordPress.' : `Saved. WordPress needs attention: ${data.sync.message || data.credentials.message}`); await qc.invalidateQueries({ queryKey: ['monetization-settings'] }); }
        catch (e) { setMessage(errorMessage(e, 'Could not save. Your changes are still here.')); }
        finally { setBusy(false); }
    }
    async function readiness() {
        setBusy(true);setMessage('Checking protected delivery…');
        try {const {data}=await api.post(`/crm/settings/monetization/markets/${form.platform_id}/sync`);setMessage(data.readiness?.ready?'Delivery checks passed and configuration synced.':`Delivery blocked: ${data.readiness?.error||'Inspect failed checks below.'}`);await qc.invalidateQueries({queryKey:['monetization-settings']});}
        catch(e){setMessage(errorMessage(e, 'Readiness check failed.'));}finally{setBusy(false);}
    }
    async function system(key, value) {
        if (reason.trim().length < 5) { setMessage('Enter an audit reason before changing global controls.'); return; }
        setBusy(true);
        try { await api.put('/crm/settings/monetization/system', { ...query.data.system, [key]: value, reason }); await qc.invalidateQueries({ queryKey: ['monetization-settings'] }); setMessage('Global controls saved. Existing purchases retain access.'); }
        catch (e) { setMessage(e.response?.data?.message || 'Could not update global controls.'); } finally { setBusy(false); }
    }
    if (query.isPending) return <p role="status" className="p-6 text-slate-500">Loading Monetize settings…</p>;
    if (query.isError) return <div role="alert" className="rounded-lg border border-red-200 p-5">Could not load settings. <button onClick={() => query.refetch()}>Try again</button></div>;
    if (!form) return <p>No authorised markets are available.</p>;
    return <form onSubmit={save} className="space-y-5">
        <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 className="text-xl font-semibold text-slate-900">Monetize settings</h2><p className="mt-1 text-sm text-slate-500">Pricing, private content and protected access. Revision {form.config_revision}.</p></div><label className="w-full md:w-64"><span className="mb-1 block text-xs font-medium text-slate-500">Market</span><select className={fieldClass} value={market || form.platform_id} onChange={e => { setMarket(e.target.value); setMessage(''); }}>{query.data.platforms.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
        <div role="tablist" aria-label="Monetize settings sections" className="flex flex-wrap gap-1 rounded-lg border border-slate-200 bg-slate-50 p-1">{sections.map((label, i) => <button type="button" role="tab" aria-selected={section === i} key={label} onClick={() => setSection(i)} className={`min-h-11 rounded-md px-4 text-sm ${section === i ? 'bg-white font-semibold text-slate-900 shadow-sm' : 'text-slate-500'}`}>{label}</button>)}</div>
        <section className="rounded-lg border border-slate-200 bg-white p-5" role="tabpanel">
            {section === 5 && <SendLoveSettings platform={form.platform_id} />}
            {section === 0 && <div className="grid gap-6 lg:grid-cols-2"><div className="space-y-3"><h3 className="font-semibold">Market rollout</h3><Check label="Enable this market" checked={form.enabled} onChange={v => update('enabled', v)} /><label className="block text-sm">Mode<select className={fieldClass} value={form.rollout_mode} onChange={e => update('rollout_mode', e.target.value)}><option value="off">Off</option><option value="sandbox">Sandbox · designated test creators</option><option value="live">Live</option></select></label>{['activation_kill_switch','checkout_kill_switch'].map(k => <Check key={k} label={names[k]} checked={form[k]} onChange={v => update(k, v)} />)}<label className="block text-sm">Sandbox creator IDs<input className={fieldClass} value={(form.test_client_ids || []).join(', ')} onChange={e => update('test_client_ids', e.target.value.split(',').map(Number).filter(Boolean))} /></label></div><div className="space-y-4"><h3 className="font-semibold">WordPress readiness</h3><div className="rounded-md bg-slate-50 p-4 text-sm leading-7"><p>{form.readiness_json?.ready ? 'Protected delivery ready' : 'Blocked · run WordPress setup and heartbeat'}</p><p>WordPress revision: {form.wp_revision} / {form.config_revision}</p><p>Last heartbeat: {form.heartbeat_at ? new Date(form.heartbeat_at).toLocaleString() : 'Not received'}</p><label className="block">Currency<select className={fieldClass} value={form.currency} onChange={e=>update('currency',e.target.value)}>{(query.data.supported_currencies||[form.currency]).map(c=><option key={c}>{c}</option>)}</select><small>Uses enabled wallet currencies. Fixed after the first pass or offer.</small></label>{Object.entries(form.readiness_json?.checks||{}).map(([name,ok])=><p key={name}>{ok?'✓':'×'} {name.replaceAll('_',' ')}</p>)}{form.readiness_json?.missing?.map(x => <p key={x}>Missing: {x}</p>)}</div><button type="button" disabled={busy} onClick={readiness} className="min-h-11 rounded-md border border-slate-300 px-4 text-sm">Run checks & sync</button><p className="text-sm text-slate-500">A successful protected-storage check is required for commerce. Test purchases never credit a live wallet.</p>{query.data.can_edit_system && <div className="space-y-2 border-t pt-4"><h3 className="font-semibold">Global emergency controls</h3><Check label="Enable Monetize globally" checked={query.data.system.enabled} onChange={v => system('enabled', v)} />{['activation_kill_switch','checkout_kill_switch'].map(k => <Check key={k} label={names[k]} checked={query.data.system[k]} onChange={v => system(k, v)} />)}</div>}</div></div>}
            {section === 1 && <div className="grid gap-5 md:grid-cols-2">{form.prices.map((p, i) => { const change = (k,v) => update('prices', form.prices.map((row,n) => n === i ? {...row,[k]:v} : row)); const subsidy = p.subsidy_mode === 'percentage' ? Number(p.price) * Number(p.subsidy_value) / 100 : Number(p.subsidy_value); return <div key={p.duration_key} className="space-y-4 rounded-lg border border-slate-200 p-5"><h3 className="text-lg font-semibold">{p.duration_label}</h3><Check label="Available" checked={p.is_active} onChange={v => change('is_active',v)} /><label className="block text-sm">Standard price · {form.currency}<input type="number" min="0" step="0.01" className={fieldClass} value={p.price} onChange={e => change('price',e.target.value)} /></label><label className="block text-sm">Paid-listing subsidy<select className={fieldClass} value={p.subsidy_mode} onChange={e => change('subsidy_mode', e.target.value)}><option value="fixed">Fixed amount</option><option value="percentage">Percentage</option></select></label><input aria-label={`${p.duration_label} subsidy`} type="number" min="0" className={fieldClass} value={p.subsidy_value} onChange={e => change('subsidy_value', e.target.value)} /><div className="border-t pt-3 text-sm leading-7"><p>Paid listing: <strong>{form.currency} {Math.max(0, p.price - subsidy).toFixed(2)}</strong></p><p>Trial or SEO boost: {form.currency} {Number(p.price).toFixed(2)}</p></div></div>; })}</div>}
            {section === 2 && <div className="space-y-5"><p className="text-sm text-slate-500">Verification rules are managed in <a className="underline" href="/settings?tab=kyc">Settings → KYC</a>. Passes and buyer access are unaffected by verification policy.</p><div className="grid gap-4 md:grid-cols-2">{Object.entries(form.offer_policy).map(([k,v]) => typeof v === 'boolean' ? <Check key={k} label={names[k] || k} checked={v} onChange={x => nested('offer_policy',k,x)} /> : <label key={k} className="text-sm">{names[k] || k}<input type="number" className={fieldClass} value={v} onChange={e => nested('offer_policy', k, Number(e.target.value))} /></label>)}</div></div>}
            {section === 4 && form.expiry_video_policy && <MonetizationAutomation form={form} update={update} automation={query.data.automation} marketName={query.data.platforms.find(p => String(p.id) === String(form.platform_id))?.name || 'This market'} savedRevision={query.data.market.config_revision} dirty={JSON.stringify([form.expiry_video_policy, form.free_pass_policy, form.teaser_policy]) !== JSON.stringify([query.data.automation.expiry, query.data.automation.free_pass, query.data.automation.teaser])} />}
            {section === 3 && <div className="grid gap-6 lg:grid-cols-2"><div className="space-y-3"><h3 className="font-semibold">Discovery surfaces</h3>{Object.entries(form.surface_policy).map(([k,v]) => <Check key={k} label={names[k] || k} checked={v} onChange={x => nested('surface_policy',k,x)} />)}</div><div className="space-y-3"><h3 className="font-semibold">Checkout & access</h3>{['kopokopo','pawapay'].map(k => <Check key={k} label={k === 'kopokopo' ? 'M-Pesa · KopoKopo' : 'PawaPay'} checked={form.checkout_policy.allowed_providers.includes(k)} onChange={v => nested('checkout_policy','allowed_providers',v ? [...form.checkout_policy.allowed_providers,k] : form.checkout_policy.allowed_providers.filter(x => x !== k))} />)}{[['device_slots','Device slots',1,3],['restore_per_hour','Restore attempts per hour',1,10]].map(([k,label,min,max]) => <label key={k} className="block text-sm">{label}<input type="number" min={min} max={max} className={fieldClass} value={form.checkout_policy[k]} onChange={e => nested('checkout_policy',k,Number(e.target.value))} /></label>)}<label className="block text-sm">Viewing grant (seconds)<input type="number" min="60" max="300" className={fieldClass} value={form.delivery_policy.grant_ttl} onChange={e => nested('delivery_policy','grant_ttl',Number(e.target.value))} /></label><p className="text-xs leading-5 text-slate-500">Sales credit the full listed price. Refund the buyer manually, then record the refund in Monetize → Sales. Wallet reversals use the existing PIN-protected adjustment.</p></div></div>}
        </section>
        {section !== 5 && <div className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-4 md:flex-row md:items-end"><label className="flex-1 text-sm">Reason for change<input required minLength={5} className={fieldClass} value={reason} onChange={e => setReason(e.target.value)} placeholder="Explain this market change" /></label><button disabled={busy} className="min-h-11 rounded-md bg-slate-900 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save & sync'}</button></div>}
        <p role="status" aria-live="polite" className="text-sm text-slate-700">{message}</p>
        <details className="rounded-lg border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-medium">Recent configuration changes</summary>{query.data.audit.map(a => <div key={a.id} className="border-b py-3 text-sm"><p>{a.reason}</p><span className="text-xs text-slate-500">{new Date(a.created_at).toLocaleString()} · Staff {a.actor_id}</span></div>)}</details>
    </form>;
}
