import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const input = 'min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-teal-600';
const button = 'inline-flex min-h-11 items-center justify-center rounded-md border border-slate-300 px-4 text-sm font-medium text-slate-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 disabled:cursor-not-allowed disabled:opacity-50';

function Artifact({ title, text }) {
    const [copied, setCopied] = useState(false);
    const [error, setError] = useState('');
    return <div className="mt-4 min-w-0"><div className="flex items-center justify-between gap-3"><h4 className="text-sm font-medium">{title}</h4><button type="button" className={button} onClick={async () => { try { await navigator.clipboard.writeText(text); setCopied(true); setError(''); } catch { setError('Select and copy the text below. Clipboard access is unavailable.'); } }}>{copied ? 'Copied' : `Copy ${title.toLowerCase()}`}</button></div><pre tabIndex={0} className="mt-2 overflow-x-auto rounded-md border border-slate-200 bg-white p-3 text-xs leading-6 text-slate-700">{text}</pre><p role="status" className="text-xs text-slate-600">{error}</p></div>;
}

export function ProviderChoices({ setup, form, onChange, error }) {
    const savedProviders = setup?.providers;
    const environmentChanged = savedProviders?.environment !== form.premium_access_environment;
    const providers = environmentChanged ? { ...savedProviders, available: [], environment: form.premium_access_environment } : savedProviders;
    const selected = form.checkout_policy.allowed_providers || [];
    const unavailableSelected = selected.filter(key => !providers?.available?.some(provider => provider.key === key));
    return <fieldset aria-describedby={error ? "monetization-provider-error" : undefined} className="space-y-3"><legend className="mb-2 text-sm font-semibold">Checkout providers · {providers?.environment || form.premium_access_environment}</legend>
        {(providers?.available || []).map(provider => <label key={provider.key} className="flex min-h-11 items-center gap-3 rounded-md border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" className="h-4 w-4 accent-teal-700" checked={selected.includes(provider.key)} onChange={e => onChange(e.target.checked ? [...selected, provider.key] : selected.filter(key => key !== provider.key))} /><span>{provider.label}</span></label>)}
        {environmentChanged ? <p className="text-sm leading-6 text-slate-600">Save this environment change, then choose from the available providers.</p> : !providers?.available?.length && <p className="text-sm leading-6 text-slate-600">No checkout provider is available for this market and environment. Enable a provider and complete its credentials in <Link className="font-medium text-teal-800 underline" to={providers?.settings_url || '/settings?tab=integrations&integrationArea=wallet'}>Settings → Wallet System</Link>, then re-check.</p>}
        {unavailableSelected.map(key => <div key={key} className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm"><p>{providers?.unavailable?.find(provider => provider.key === key)?.message || `${key} is unavailable for this market. Remove it before saving.`}</p><button type="button" className={`${button} mt-2 bg-white`} onClick={() => onChange(selected.filter(provider => provider !== key))}>Remove unavailable {key === 'pawapay' ? 'PawaPay' : 'KopoKopo'}</button></div>)}
        <p id="monetization-provider-error" role={error ? 'alert' : undefined} className="text-sm text-red-700">{error}</p>
    </fieldset>;
}

export default function MonetizationSetup({ setup, form, update, nested, busy, dirty, onAction, onCheck, onSection, systemControls, providerError, supportedCurrencies }) {
    const host = setup?.server?.host_setup?.config ? setup.server.host_setup : null;
    const [technical, setTechnical] = useState(false);
    const live = setup?.is_live;
    return <div className="space-y-6">
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 pb-5"><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{setup?.market?.name} · Market #{form.platform_id} · {form.currency}</p><h3 className="mt-2 text-lg font-semibold text-slate-900">{live ? 'Live market · setup and health' : 'Set up this market, one step at a time'}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{live ? 'Current live settings remain in place. Use these checks to verify the connection and delivery.' : 'Connect the site, resolve any server steps and review selling settings. The market stays Off until you explicitly enable it.'}</p></div><span className={`rounded-md px-3 py-2 text-sm font-semibold ${live ? 'bg-teal-50 text-teal-800' : 'bg-slate-100 text-slate-700'}`}>{live ? 'Live' : form.rollout_mode === 'sandbox' ? 'Sandbox' : 'Off'}</span></div>
        <ol className="divide-y divide-slate-200">{(setup?.gates || []).map((gate, index) => <li key={gate.key} className="grid gap-4 py-5 md:grid-cols-[2rem_1fr]">
            <span aria-hidden="true" className={`flex h-8 w-8 items-center justify-center rounded-full border text-sm font-medium ${gate.passed ? 'border-teal-200 bg-teal-50 text-teal-800' : 'border-slate-300 text-slate-600'}`}>{gate.passed ? '✓' : index + 1}</span>
            <div className="min-w-0 space-y-3"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><h4 className="font-semibold text-slate-900">{gate.label}</h4><span className={`text-xs ${gate.passed ? 'text-teal-700' : 'text-slate-500'}`}>{gate.passed ? 'Verified' : 'Needs attention'}</span></div><p className="max-w-3xl break-words text-sm leading-6 text-slate-600">{gate.message}</p>
                {gate.key === 'connection' && <><dl className="grid gap-3 rounded-md bg-slate-50 p-4 text-sm"><div><dt className="text-xs font-medium text-slate-500">CRM WordPress API address</dt><dd className="mt-1 break-all">{setup.configured_url || 'Not configured · set it in Settings → Markets'}</dd></div><div><dt className="text-xs font-medium text-slate-500">Reported WordPress address</dt><dd className="mt-1 break-all">{setup.reported_url || 'Run a check to discover the address'}</dd></div></dl><div className="flex flex-wrap gap-3"><button type="button" disabled={busy || dirty} onClick={() => onAction('connect')} className={button}>Connect WordPress</button><button type="button" disabled={busy || dirty} onClick={onCheck} className={button}>Run checks & sync</button><Link className={button} to={`/settings?tab=integrations&integrationArea=markets&platform_id=${form.platform_id}`}>Open WordPress connection settings</Link>{setup.canonical_mismatch && setup.repair_url && <button type="button" disabled={busy || dirty} onClick={() => onAction('canonical')} className={`${button} border-teal-300 text-teal-800`}>Use reported canonical URL</button>}</div>{dirty && <p className="text-sm text-amber-800">Save your draft before running setup actions. Checks use the saved configuration.</p>}</>}
                {gate.key === 'server' && <>{(setup.server?.issues || []).filter(issue => form.offer_policy.videos_enabled || !String(issue.code || '').startsWith('ffmpeg') && issue.code !== 'php_exec_disabled').map(issue => <p key={issue.code} className="text-sm leading-6 text-slate-600">{issue.message}</p>)}{host && <details open={!gate.passed} className="rounded-md border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer py-1 font-medium">Server step · {setup.market.name}</summary><p className="mt-2 text-sm leading-6 text-slate-600">{host.instructions}</p><dl className="mt-3 space-y-2 text-xs"><div><dt className="font-medium">Public root</dt><dd className="break-all">{host.public_root}</dd></div><div><dt className="font-medium">Intended private storage</dt><dd className="break-all">{host.storage_location}</dd></div></dl><Artifact title="WordPress config" text={host.config} /><button type="button" className={`${button} mt-3`} aria-expanded={technical} onClick={() => setTechnical(value => !value)}>Technical verification {technical ? '−' : '+'}</button>{technical && <><Artifact title="Verification commands" text={host.commands} /><p className="mt-2 text-xs leading-6 text-slate-600">Detected FFmpeg: {setup.server.video.path || 'Not found'}. PHP execution: {setup.server.video.exec_available ? 'available' : 'unavailable'}. libx264: {setup.server.video.libx264 ? 'available' : 'missing'}. AAC: {setup.server.video.aac ? 'available' : 'missing'}.</p></>}</details>}<button type="button" disabled={busy || dirty} onClick={onCheck} className={button}>Re-check server</button></>}
                {gate.key === 'wallet' && <div className="flex flex-wrap items-end gap-4"><label className="block w-full text-sm sm:w-64">Intended wallet environment<select className={input} value={form.premium_access_environment} disabled={live} onChange={e => { update('premium_access_environment', e.target.value); nested('checkout_policy', 'allowed_providers', []); }}><option value="sandbox">Sandbox · test payments</option><option value="production">Production</option></select></label><Link className="inline-flex min-h-11 items-center text-sm font-medium text-teal-800 underline" to={setup.providers.settings_url}>Open Wallet System</Link><p className="w-full text-xs text-slate-500">Wallet System mode: {setup.wallet_mode}. Selecting production here does not enable the market.</p></div>}
                {gate.key === 'providers' && <ProviderChoices setup={setup} form={form} error={providerError} onChange={value => nested('checkout_policy', 'allowed_providers', value)} />}
                {gate.key === 'pricing' && <div className="flex flex-wrap gap-3"><button type="button" className={button} onClick={() => onSection(1)}>Review pass pricing</button><button type="button" className={button} onClick={() => onSection(2)}>Review offers & limits</button><label className="block w-full text-sm sm:w-48">Wallet currency<select className={input} value={form.currency} onChange={e => update('currency', e.target.value)}>{supportedCurrencies.map(currency => <option key={currency}>{currency}</option>)}</select></label></div>}
                {gate.key === 'delivery' && <><div className="grid gap-2 sm:grid-cols-2">{Object.entries(form.readiness_json?.checks || {}).map(([key, passed]) => <div key={key} className="text-sm"><span className={passed ? 'text-teal-800' : 'text-amber-800'}>{passed ? '✓ Passed' : 'Needs attention'} · {key.replaceAll('_', ' ')}</span>{!passed && form.readiness_json?.details?.[key] && <p className="mt-1 text-xs leading-5 text-slate-600">{form.readiness_json.details[key]}</p>}</div>)}</div><p className="text-xs text-slate-500">WordPress revision {form.wp_revision} / {form.config_revision} · Last check {setup.checked_at ? new Date(setup.checked_at).toLocaleString() : 'not run'}</p></>}
                {gate.key === 'activation' && <><button type="button" className="min-h-11 rounded-md bg-teal-700 px-5 text-sm font-semibold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 disabled:cursor-not-allowed disabled:opacity-50" disabled={busy || dirty || !setup.ready_to_enable || live} onClick={() => onAction('activate')}>{live ? 'Market is live' : 'Enable live market'}</button><p className="text-xs leading-5 text-slate-500">This action is audited and enables live selling. Readiness does not prove a real payment, refund, access restoration or settlement.</p></>}
            </div>
        </li>)}</ol>
        <details className="border-t border-slate-200 pt-4"><summary className="cursor-pointer py-2 text-sm font-semibold">Market controls and global sales pauses</summary><div className="mt-3 space-y-3"><label className="block text-sm">Market mode<select className={input} value={form.rollout_mode} onChange={e => { update('rollout_mode', e.target.value); if (e.target.value === 'off') update('enabled', false); if (e.target.value === 'sandbox') { update('enabled', true); update('premium_access_environment', 'sandbox'); nested('checkout_policy', 'allowed_providers', []); } }}><option value="off">Off</option><option value="sandbox">Sandbox · designated test creators</option>{live && <option value="live">Live</option>}</select></label>{['activation_kill_switch', 'checkout_kill_switch'].map((key, i) => <label key={key} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={!!form[key]} onChange={e => update(key, e.target.checked)} />{i === 0 ? 'Pause new pass activation' : 'Pause new purchases'}</label>)}<label className="block text-sm">Sandbox creator IDs<input className={input} value={(form.test_client_ids || []).join(', ')} onChange={e => update('test_client_ids', e.target.value.split(',').map(Number).filter(Boolean))} /></label>{systemControls}</div></details>
    </div>;
}
