import React, {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import api from '../../../services/api';
const field='min-h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm';
export default function SendLoveSettings({platform}) {
    const query=useQuery({queryKey:['send-love-settings',platform],enabled:Boolean(platform),queryFn:async()=>(await api.get(`/crm/settings/send-love/${platform}`)).data});
    const [form,setForm]=useState(null),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),[preview,setPreview]=useState(1000);
    useEffect(()=>{if(query.data){setForm(query.data.market);setPreview(query.data.market.default_preset);}},[query.data]);
    const update=(key,value)=>setForm(f=>({...f,[key]:value}));
    const nested=(key,part,value)=>update(key,{...form[key],[part]:value});
    async function save(){setBusy(true);setErrors({});try{const {data}=await api.put(`/crm/settings/send-love/${platform}`,{...form,reason});setForm(data.market);setMessage(data.sync.status==='synced'?'Saved. WordPress acknowledged this revision.':`Saved locally. ${data.sync.message}`);}catch(e){setErrors(e.response?.data?.errors||{});setMessage(e.response?.data?.message||'Could not save. Your values are kept.');}finally{setBusy(false);}}
    async function sync(){setBusy(true);try{const {data}=await api.post(`/crm/settings/send-love/${platform}/sync`);setMessage(data.sync.status==='synced'?'WordPress acknowledged this revision.':data.sync.message);await query.refetch();}catch(e){setMessage('Could not reach WordPress.');}finally{setBusy(false);}}
    async function globalPause(){if(reason.trim().length<5){setMessage('Enter a reason before changing the global pause.');return;}setBusy(true);try{const {data}=await api.put('/crm/settings/send-love-system',{send_love_kill_switch:!query.data.system.send_love_kill_switch,config_revision:query.data.system.config_revision,reason});await query.refetch();const failed=Object.values(data.sync).filter(x=>x.status!=='synced').length;setMessage(failed?'Global pause saved. '+failed+' markets need a sync retry.':'Global Send love pause updated and synced.');}catch(e){setMessage(e.response?.data?.message||'Could not update global pause.');}finally{setBusy(false);}}
    if(query.isPending)return <p role="status">Loading Send love settings…</p>;
    if(query.isError)return <div role="alert">Could not load Send love settings. <button type="button" onClick={()=>query.refetch()}>Try again</button></div>;
    if(!form)return null;
    const check=(label,key)=> <label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form[key])} onChange={e=>update(key,e.target.checked)}/>{label}</label>;
    return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-semibold">Send love</h3><p className="mt-1 text-sm text-slate-500">Private gifts from visitors. WordPress revision {form.wp_revision} / {form.config_revision}.</p></div><button type="button" className={field+' w-auto'} disabled={busy} onClick={sync}>Retry sync</button></div>
        <div className="grid gap-6 lg:grid-cols-2"><div className="space-y-3">{check('Enable Send love','enabled')}{check('Pause new gifts','kill_switch')}<label className="block text-sm">Mode<select className={field} value={form.rollout_mode} onChange={e=>update('rollout_mode',e.target.value)}>{['off','sandbox','live'].map(v=><option key={v}>{v}</option>)}</select></label><label className="block text-sm">Currency<input className={field} value={form.currency} onChange={e=>update('currency',e.target.value.toUpperCase())}/><small className="text-slate-500">Fixed once a gift exists.</small></label><label className="block text-sm">Sandbox creator IDs<input className={field} value={(form.test_client_ids||[]).join(', ')} onChange={e=>update('test_client_ids',e.target.value.split(',').map(Number).filter(Boolean))}/></label>
        <div><h4 className="text-sm font-semibold">Mobile money providers</h4>{['kopokopo','pawapay'].map(p=><label className="flex min-h-11 items-center gap-2 text-sm" key={p}><input type="checkbox" checked={form.allowed_providers_json.includes(p)} onChange={e=>update('allowed_providers_json',e.target.checked?[...form.allowed_providers_json,p]:form.allowed_providers_json.filter(x=>x!==p))}/>{p==='kopokopo'?'M-Pesa · KopoKopo':'pawaPay'}</label>)}{errors.allowed_providers_json&&<p role="alert" className="text-sm text-rose-700">{errors.allowed_providers_json[0]}</p>}</div></div>
        <div className="space-y-4"><div className="aspect-[1.586] max-w-sm rounded-lg border border-stone-300 bg-stone-100 p-6 text-stone-800"><div className="flex justify-between text-xs font-bold tracking-widest"><span>EXOTIC</span><span>LOVE · GIFT</span></div><p className="mt-6 text-xs uppercase">For Daisy</p><p className="text-3xl font-bold">{form.currency} {Number(preview).toLocaleString()}</p><p className="mt-2 text-sm">{preview>=5000?'Chop money, chop life!':preview>=1000?'Spoil yourself properly':preview>=500?'Spoil yourself':'A little something sweet'}</p></div><div className="flex gap-2">{form.presets_json.map((n,i)=><button type="button" className={field+' w-auto'} key={i} onClick={()=>setPreview(n)}>{form.currency} {n}</button>)}</div><div className="grid grid-cols-3 gap-2">{form.presets_json.map((n,i)=><label className="text-sm" key={i}>Preset {i+1}<input type="number" className={field} value={n} onChange={e=>update('presets_json',form.presets_json.map((x,j)=>i===j?Number(e.target.value):x))}/></label>)}</div>
        {[['default_preset','Default amount'],['custom_min','Minimum amount'],['custom_max','Maximum amount'],['creator_share_bps','Creator share (basis points; 10,000 = 100%)']].map(([k,label])=><label key={k} className="block text-sm">{label}<input className={field} type="number" value={form[k]} onChange={e=>update(k,Number(e.target.value))}/></label>)}</div></div>
        <div className="grid gap-3 border-t border-slate-200 pt-4 md:grid-cols-2"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.copy_policy_json.playful_copy} onChange={e=>nested('copy_policy_json','playful_copy',e.target.checked)}/>Playful card copy</label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.message_policy_json.enabled} onChange={e=>nested('message_policy_json','enabled',e.target.checked)}/>Allow private notes</label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.message_policy_json.sender_name} onChange={e=>nested('message_policy_json','sender_name',e.target.checked)}/>Allow sign-offs</label><label className="text-sm">Note limit (characters)<input type="number" max="140" min="1" className={field} value={form.message_policy_json.max_len} onChange={e=>nested('message_policy_json','max_len',Number(e.target.value))}/></label>{[['per_phone_daily_amount','Per-phone daily amount limit'],['attempts_per_10min','Attempts per ten minutes']].map(([k,label])=><label key={k} className="text-sm">{label}<input type="number" className={field} value={form.limits_json[k]} onChange={e=>nested('limits_json',k,Number(e.target.value))}/></label>)}</div>
        <p className="text-sm text-slate-500">Active listings only. Contact details and links are blocked in notes. Sender numbers are shared only with consent. Sandbox gifts never credit a wallet.</p>
        <label className="block text-sm">Reason for change<input className={field} value={reason} minLength="5" onChange={e=>setReason(e.target.value)}/></label><div className="flex flex-wrap gap-2"><button type="button" onClick={save} disabled={busy||reason.trim().length<5} className="min-h-11 rounded-md bg-slate-900 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Save & sync Send love'}</button>{query.data.can_edit_system&&<button type="button" disabled={busy} className={field+' w-auto'} onClick={globalPause}>{query.data.system.send_love_kill_switch?'Resume Send love globally':'Pause Send love globally'}</button>}</div><p role="status" className="text-sm">{message}</p>{Object.entries(errors).filter(([k])=>k!=='allowed_providers_json').map(([k,v])=><p role="alert" key={k} className="text-sm text-rose-700">{k}: {v[0]}</p>)}
    </div>;
}
